<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADS29" name="Test" tests="15" failures="14" timestamp="17 Jul 2017 11:47:15 GMT" time="2.761" errors="0">
  <testcase name="HS_Premise_First_Name_Check_TC018" time="0.268" classname="J_POC.J_POC.HS_TS007_Premise_Name_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_First_Name is Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;14&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_First_Name is Mandatory expected:<0> but was:<14>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS007_Premise_Name_Check.HS_Premise_First_Name_Check_TC018(HS_TS007_Premise_Name_Check.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_First_Name_Check_TC018 -->
  <testcase name="HS_Premise_Last_Name_Check_TC019" time="0.011" classname="J_POC.J_POC.HS_TS007_Premise_Name_Check">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Last_Name is Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Last_Name is Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS007_Premise_Name_Check.HS_Premise_Last_Name_Check_TC019(HS_TS007_Premise_Name_Check.java:61)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Last_Name_Check_TC019 -->
  <testcase name="HS_SJPayments_AccountNumber_Check_TC028" time="0.013" classname="J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check">
    <failure type="junit.framework.AssertionFailedError" message="Payments From Partner Account Number check is as Expected  expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Payments From Partner Account Number check is as Expected  expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_AccountNumber_Check_TC028(HS_TS010_PaymentsFromPartner_Check.java:36)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_AccountNumber_Check_TC028 -->
  <testcase name="HS_SJPayments_ChargeType_Check_TC029" time="0.008" classname="J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check">
    <failure type="junit.framework.AssertionFailedError" message="Payments From Partner Charge Type Check is Failed at Partner_Account_Number= ACCD101N8776123 Reason as  expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Payments From Partner Charge Type Check is Failed at Partner_Account_Number= ACCD101N8776123 Reason as  expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_ChargeType_Check_TC029(HS_TS010_PaymentsFromPartner_Check.java:68)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_ChargeType_Check_TC029 -->
  <testcase name="HS_SJPayments_Invoice_Number_Check_TC030" time="0.016" classname="J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check">
    <failure type="junit.framework.AssertionFailedError" message="Payments From Partner Charge Type Check is Failed at Partner_Account_Number= ACCD101N8776123 Reason as  expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Payments From Partner Charge Type Check is Failed at Partner_Account_Number= ACCD101N8776123 Reason as  expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Invoice_Number_Check_TC030(HS_TS010_PaymentsFromPartner_Check.java:97)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Invoice_Number_Check_TC030 -->
  <testcase name="HS_SJPayments_Partner_ChargeSign_Check_TC032" time="0.011" classname="J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check">
    <failure type="junit.framework.AssertionFailedError" message="Payments From Partner Charge Sign Check is Failed at Partner_Account_Number= ACCD101N8776123 expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Payments From Partner Charge Sign Check is Failed at Partner_Account_Number= ACCD101N8776123 expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Partner_ChargeSign_Check_TC032(HS_TS010_PaymentsFromPartner_Check.java:154)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Partner_ChargeSign_Check_TC032 -->
  <testcase name="HS_SJPayments_Partner_Record_Type_Check_TC033" time="0.011" classname="J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check">
    <failure type="junit.framework.AssertionFailedError" message="Payments From Partner Record Type Check is Failed at Partner_Account_Number= ACCD101N9880765 expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Payments From Partner Record Type Check is Failed at Partner_Account_Number= ACCD101N9880765 expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Partner_Record_Type_Check_TC033(HS_TS010_PaymentsFromPartner_Check.java:183)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Partner_Record_Type_Check_TC033 -->
  <testcase name="HS_SJPayments_Transaction_Amount_Check_TC031" time="0.013" classname="J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check">
    <failure type="junit.framework.AssertionFailedError" message="Payments From Partner Partner Transaction Amount Check is Failed at Partner_Account_Number= ACCD101N8776123 Amount value not zero, but we got count as  expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Payments From Partner Partner Transaction Amount Check is Failed at Partner_Account_Number= ACCD101N8776123 Amount value not zero, but we got count as  expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS010_PaymentsFromPartner_Check.HS_SJPayments_Transaction_Amount_Check_TC031(HS_TS010_PaymentsFromPartner_Check.java:125)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_SJPayments_Transaction_Amount_Check_TC031 -->
  <testcase name="HS_AEPAudit_Date_Check_TC025" time="0.022" classname="J_POC.J_POC.HS_TS009_AEPAudit_Details_Check">
    <failure type="junit.framework.AssertionFailedError" message="AEPAudit Date Check is Failed at UniqueID= D3527056787843525678 Reason as  expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: AEPAudit Date Check is Failed at UniqueID= D3527056787843525678 Reason as  expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at J_POC.J_POC.HS_TS009_AEPAudit_Details_Check.HS_AEPAudit_Date_Check_TC025(HS_TS009_AEPAudit_Details_Check.java:45)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPAudit_Date_Check_TC025 -->
  <testcase name="HS_AEPAudit_ProductCodes_Null_Check_TC026" time="2.001" classname="J_POC.J_POC.HS_TS009_AEPAudit_Details_Check">
    <failure type="com.mysql.jdbc.CommunicationsException" message="Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:434)
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.&amp;lt;init&amp;gt;(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.&amp;lt;init&amp;gt;(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at J_POC.J_POC.HS_TS009_AEPAudit_Details_Check.HS_AEPAudit_ProductCodes_Null_Check_TC026(HS_TS009_AEPAudit_Details_Check.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


** END NESTED EXCEPTION **



Last packet sent to the server was 1 ms ago.">
      <![CDATA[com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at J_POC.J_POC.HS_TS009_AEPAudit_Details_Check.HS_AEPAudit_ProductCodes_Null_Check_TC026(HS_TS009_AEPAudit_Details_Check.java:60)


** END NESTED EXCEPTION **



Last packet sent to the server was 1 ms ago.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2847)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at J_POC.J_POC.HS_TS009_AEPAudit_Details_Check.HS_AEPAudit_ProductCodes_Null_Check_TC026(HS_TS009_AEPAudit_Details_Check.java:60)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPAudit_ProductCodes_Null_Check_TC026 -->
  <testcase name="HS_AEPCustomer_FirstName_Check_TC020" time="0.143" classname="J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 8, Size: 8">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_FirstName_Check_TC020(HS_TS008_AEPCustomer_Details_Check.java:48)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_FirstName_Check_TC020 -->
  <testcase name="HS_AEPCustomer_LastName_Check_TC021" time="0.052" classname="J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check">
    <failure type="junit.framework.ComparisonFailure" message="AEP Partner Last name Check is Failed expected:&amp;lt;Lokesh&amp;gt; but was:&amp;lt;null&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: AEP Partner Last name Check is Failed expected:<Lokesh> but was:<null>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_LastName_Check_TC021(HS_TS008_AEPCustomer_Details_Check.java:101)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_LastName_Check_TC021 -->
  <testcase name="HS_AEPCustomer_MailingAddressState_Check_TC022" time="0.055" classname="J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check"/>
  <testcase name="HS_AEPCustomer_PremisesAddressZipPlus4_Check_TC023" time="0.047" classname="J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check">
    <failure type="junit.framework.AssertionFailedError" message="AEP Partner Premises Address Zip Plus4 Pattern Check is Failed expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: AEP Partner Premises Address Zip Plus4 Pattern Check is Failed expected:<false> but was:<true>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:174)
	at J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_PremisesAddressZipPlus4_Check_TC023(HS_TS008_AEPCustomer_Details_Check.java:246)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_PremisesAddressZipPlus4_Check_TC023 -->
  <testcase name="HS_AEPCustomer_UniqueID_Check_TC024" time="0.039" classname="J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check">
    <failure type="junit.framework.ComparisonFailure" message="AEP Partner User ID Check is Failed expected:&amp;lt;lok@[]]124673229&amp;gt; but was:&amp;lt;lok@[]124673229&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: AEP Partner User ID Check is Failed expected:<lok@[]]124673229> but was:<lok@[]124673229>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at J_POC.J_POC.HS_TS008_AEPCustomer_Details_Check.HS_AEPCustomer_UniqueID_Check_TC024(HS_TS008_AEPCustomer_Details_Check.java:285)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_AEPCustomer_UniqueID_Check_TC024 -->
</testsuite> <!-- Test -->
